In [1]:
import numpy as np
# ceating an array
arr1 = np.array([1,2,3,4,5,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5 5]
<class 'numpy.ndarray'>
(6,)


In [9]:
# creating 2d array
arr2 = np.array([1,2,3,4,5])
print(arr2.reshape(1,5))
print(arr2)
print(arr2.shape)
print(type(arr2))

[[1 2 3 4 5]]
[1 2 3 4 5]
(5,)
<class 'numpy.ndarray'>


In [11]:
arr3 = np.array([[1,2,3,4,5],[2,3,4,5,6]])
print(arr3)
print(arr3.shape)

[[1 2 3 4 5]
 [2 3 4 5 6]]
(2, 5)


In [14]:
arr1.reshape(6,1)
print(arr1)
print(arr1.shape)

[1 2 3 4 5 5]
(6,)


In [15]:
# we can create arry with elemnets using np.arange
arr4 = np.arange(0,10,2)
print(arr4)

[0 2 4 6 8]


In [17]:
arr5 = np.arange(0,15,2).reshape(8,1)
# it will be a 2d array
print(arr5)

[[ 0]
 [ 2]
 [ 4]
 [ 6]
 [ 8]
 [10]
 [12]
 [14]]


In [18]:
# using element wise operations
a1 = np.array([2,4,6,8,9])
a2 = np.array([3,6,9,11,15])

print(a2-a1)
print(a2+a1)
print(a2*a1)
print(a2/a1)
print(np.sqrt(a1))
print(np.sin(a1))

[1 2 3 3 6]
[ 5 10 15 19 24]
[  6  24  54  88 135]
[1.5        1.5        1.5        1.375      1.66666667]
[1.41421356 2.         2.44948974 2.82842712 3.        ]
[ 0.90929743 -0.7568025  -0.2794155   0.98935825  0.41211849]


In [19]:
# array indexing and slicing
a22 = np.array([[1,2,3,4],[5,6,7,8],[11,2,34,54]])
print(a22)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [11  2 34 54]]


In [20]:
print(a22[1][3])

8


In [24]:
print(a22[1:])
print(a22[1:,2:])

[[ 5  6  7  8]
 [11  2 34 54]]
[[ 7  8]
 [34 54]]


In [25]:
# modifying elements
a22[0][0]=999
print(a22)

[[999   2   3   4]
 [  5   6   7   8]
 [ 11   2  34  54]]


In [26]:
# we also change with many values
a22[1:]=99
print(a22)

[[999   2   3   4]
 [ 99  99  99  99]
 [ 99  99  99  99]]


In [27]:
# statical calculation
asd = np.array([1,2,3,5,6,7,8,10,12,3,24])
print("Mean:",np.mean(asd))
print("Varieance:",np.var(asd))
print("Standard deviation:",np.std(asd))

Mean: 7.363636363636363
Varieance: 38.231404958677686
Standard deviation: 6.183154935684346


In [29]:
#logical operations 
print(a22>5)

[[ True False False False]
 [ True  True  True  True]
 [ True  True  True  True]]


In [30]:
print(a22[a22>5])

[999  99  99  99  99  99  99  99  99]


In [31]:
print(a22[(a22>0) & (a22<10)])

[2 3 4]
